# Generated by Django 2.1.4 on 2018-12-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibary', '0004_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_about',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
