# Generated by Django 2.1.4 on 2018-12-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibary', '0006_auto_20181218_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_edit_status', 'Set status of book'))},
        ),
    ]
