# Generated by Django 2.1.4 on 2018-12-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalLibary', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=4000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to='LocalLibary.Author')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
